todaApp/main/routes.py
from flask import render_template, Blueprint 
from todaApp.models import Task, Project, User
from flask_login import current_user, login_required


main = Blueprint('main', __name__)

@main.route("/")
@login_required
def home():
    tasks= Task.query.filter_by(completed=False, user=current_user.id).order_by(Task.due_date).all()
    tasks_complete = Task.query.filter_by(completed=True, user=current_user.id).order_by(Task.due_date).all()
    projects = Project.query.filter_by(user=current_user.id).all()
    return render_template('home.html', tasks=tasks, projects=projects, tasks_complete=tasks_complete)

todaApp/tasks/routes.py
from flask import render_template, request, redirect, url_for, abort, Blueprint
from todaApp import db
from todaApp.models import Task, Project, User
from todaApp.tasks.forms import NewProjectForm, NewTaskForm
from flask_login import current_user, login_required


tasks = Blueprint('tasks', __name__)


@tasks.route("/project/new", methods=['GET', 'POST'])
@login_required
def newProject():
    form = NewProjectForm()
    if form.validate_on_submit():
        project = Project(
            title = form.title.data,
            description = form.description.data,
            due_date = form.due_date.data,
            user=current_user.id
        )
        db.session.add(project)
        db.session.commit()
        return redirect(url_for('main.home'))
    projects = Project.query.filter_by(user=current_user.id).all()
    return render_template('new-project.html', form=form,  legend='New Project', projects=projects)

@tasks.route("/project/update/<int:project_id>", methods=['GET', 'POST'])
@login_required
def update_project(project_id):
    project = Project.query.get_or_404(project_id)
    form = NewProjectForm()
    if request.method =='GET':
        form.title.data = project.title
        form.description.data = project.description
        form.due_date.data = project.due_date
    elif form.validate_on_submit():
        project.title = form.title.data
        project.description = form.description.data
        project.due_date = form.due_date.data
        db.session.commit()
        return redirect(url_for('tasks.single_project', project_id=project_id))
    projects = Project.query.filter_by(user=current_user.id).all()
    return render_template('new-project.html', form=form,  legend='Update Project', projects=projects)


@tasks.route("/project/delete/<int:project_id>", methods=['GET', 'POST'])
@login_required
def delete_project(project_id):
    project = Project.query.get_or_404(project_id)
    task = Task.query.filter_by(project=project_id)
    db.session.delete(project)
    db.session.commit()
    return redirect(url_for('main.home'))


@tasks.route("/project/single/<int:project_id>", methods=['GET', 'POST'])
@login_required
def single_project(project_id):
    tasks= Task.query.filter_by(completed=False, project=project_id, user=current_user.id).order_by(Task.due_date).all()
    tasks_complete = Task.query.filter_by(completed=True, project=project_id, user=current_user.id).order_by(Task.due_date).all()
    project = Project.query.get_or_404(project_id)
    projects = Project.query.filter_by(user=current_user.id).all()
    return render_template('project.html', projects=projects, tasks=tasks, 
                            project=project, tasks_complete=tasks_complete)


@tasks.route("/task/new", methods=['GET', 'POST'])
@login_required
def newTask():
    form = NewTaskForm()
    form.project.choices = [(p.id, p.title) for p in Project.query.filter_by(user=current_user.id).all()] 
    if form.validate_on_submit():
        tasks=Task(
            title=form.title.data,
            description=form.description.data,
            project=form.project.data,
            due_date=form.due_date.data,
            user=current_user.id            
        )
        db.session.add(tasks)
        db.session.commit()
        return redirect(url_for('main.home'))
    projects = Project.query.filter_by(user=current_user.id).all()
    return render_template('new-task.html', form=form, legend='New Task', projects=projects)


@tasks.route("/task/update/<int:todo_id>", methods=['GET', 'POST'])
@login_required
def update_task(todo_id):
    task = Task.query.get_or_404(todo_id)
    form = NewTaskForm()
    form.project.choices = [(p.id, p.title) for p in Project.query.filter_by(user=current_user.id).all()]
    if request.method =='GET':
        form.title.data = task.title
        form.description.data = task.description
        form.project.data = task.project
        form.due_date.data = task.due_date
    elif form.validate_on_submit():
        task.title = form.title.data
        task.description = form.description.data
        task.project = form.project.data
        task.due_date = form.due_date.data
        db.session.commit()
        return redirect(url_for('main.home'))
    projects = Project.query.filter_by(user=current_user.id).all()
    return render_template('new-task.html', form=form,  legend='Update task', projects=projects)

@tasks.route("/task/complete/<int:todo_id>", methods=['GET', 'POST'])
@login_required
def complete_task(todo_id):
    task = Task.query.get_or_404(todo_id)
    task.completed = not (task.completed)
    db.session.commit()
    return redirect(url_for('main.home'))



@tasks.route("/task/delete/<int:todo_id>", methods=['GET', 'POST'])
@login_required
def delete_task(todo_id):
    task = Task.query.get_or_404(todo_id)
    db.session.delete(task)
    db.session.commit()
    return redirect(url_for('main.home'))

todaApp/users/routes.py
import os
from flask import render_template, request, redirect, url_for, abort, Blueprint, current_app
from todaApp import db, bcrypt
from todaApp.models import Project, User
from todaApp.users.forms import (RegistrationForm, loginForm,  UpdateAccountForm,
                                RequestResetForm, ResetPasswordForm)
from flask_login import login_user, current_user, logout_user, login_required
from todaApp.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    form= RegistrationForm()
    if form.validate_on_submit():
        hashed_pass = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pass)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    form = loginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page=request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))

    return render_template('login.html', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data :
            
            try :
                current_picture = os.path.join(current_app.root_path, 'static/img/profile_pict', current_user.image_file)
                os.remove(current_picture)
            except:
                pass
            
            picture_file= save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data =  current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='img/profile_pict/'+current_user.image_file)

    projects = Project.query.filter_by(user=current_user.id).all()
    return render_template('account.html', image_file=image_file, form=form, projects=projects)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user=User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        print('masuk')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', form=form)

todaApp/templates/home.html
{% extends 'layout.html'%}

{% block content %}
<div class="wrapper">
    {% include 'sidebar.html' %}
    <div id="content">
        <!-- Toggler  -->
        <div class="toggler">
            <button type="button" id="sidebarCollapse" class="btn btn-info">
                <i class="fas fa-align-left"></i>
                <span></span>
            </button>
        </div>

        <!-- Task -->
        <div class="task-content">

            <div class="scroll-area-sm">
                <perfect-scrollbar class="ps-show-limits">
                    <div style="position: static;" class="ps ps--active-y">
                        <div class="ps-content">
                            <h5>On Going Tasks</h5>
                            <ul class=" list-group list-group-flush">
                                {% for task in tasks %}
                                <li class="list-group-item">
                                    <div class="todo-indicator bg-warning"></div>
                                    <div class="widget-content p-0">
                                        <div class="widget-content-wrapper">
                                            <div class="widget-content-left mr-2">
                                                <button class="border-0 btn-transition btn btn-outline-primary">
                                                    <a href="{{ url_for('tasks.complete_task', todo_id=task.id) }}">
                                                        <i class="fa fa-check"></i>
                                                    </a>
                                                </button>
                                            </div>
                                            <div class="widget-content-left">
                                                <div class="widget-heading">{{task.title}} <div
                                                        class="badge badge-success ml-2">
                                                        {{task.due_date.strftime('%d-%m-%Y')}}</div>
                                                </div>
                                                <div class="widget-subheading">
                                                    <a href="{{url_for('tasks.update_project', project_id=task.project)}}"><strong>{{ task.task.title}}</strong></a> <br>
                                                    <i>{{task.description}}</i>
                                                </div>
                                            </div>
                                            <div class="widget-content-right">
                                                <button class="border-0 btn-transition btn btn-outline-primary">
                                                    <a href="{{ url_for('tasks.update_task', todo_id=task.id) }}"><i
                                                            class="far fa-edit"></i></a>
                                                </button>
                                                <button class="border-0 btn-transition btn btn-outline-danger">
                                                    <a href="{{ url_for('tasks.delete_task', todo_id=task.id) }}"><i
                                                            class="fa fa-trash"></i> </a>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>

                            <!-- completed task -->
                            <br>
                            <br>
                            <h5>Completed Tasks</h5>
                            <ul class=" list-group list-group-flush">
                                {% for ctask in tasks_complete %}
                                <li class="list-group-item">
                                    <div class="todo-indicator bg-warning"></div>
                                    <div class="widget-content p-0">
                                        <div class="widget-content-wrapper" style="opacity: 0.2;">
                                            <div class="widget-content-left mr-2">
                                                <button class="border-0 btn-transition btn btn-outline-primary">
                                                    <a href="{{ url_for('tasks.complete_task', todo_id=ctask.id) }}">
                                                        <i class="fa fa-times"></i>
                                                    </a>
                                                </button>
                                            </div>
                                            <div class="widget-content-left">
                                                <div class="widget-heading">{{ctask.title}} <div
                                                        class="badge badge-success ml-2">
                                                        {{ctask.due_date.strftime('%d-%m-%Y')}}</div>
                                                </div>
                                                <div class="widget-subheading">
                                                    <a href="{{url_for('tasks.update_project', project_id=ctask.project)}}"><strong>{{ ctask.task.title}}</strong></a> <br>
                                                    <i>{{ctask.description}}</i>
                                                </div>
                                            </div>
                                            <div class="widget-content-right">
                                                <button class="border-0 btn-transition btn btn-outline-primary">
                                                    <a href="{{ url_for('tasks.update_task', todo_id=ctask.id) }}">
                                                        <i class="far fa-edit"></i>
                                                    </a>
                                                </button>
                                                <button class="border-0 btn-transition btn btn-outline-danger">
                                                    <a href="{{ url_for('tasks.delete_task', todo_id=ctask.id) }}">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                            <!-- end completed task -->
                          
                        </div>
                    </div>
                </perfect-scrollbar>
            </div>
            <div class="d-block text-right card-footer">
                <a href="{{url_for('tasks.newProject')}}"> <button class="btn btn-success">Add Project</button></a>
                <a href="{{url_for('tasks.newTask')}}"><button class="btn btn-primary">Add Task</button></a>
            </div>
            <!-- Batas -->
        </div>

    </div>

</div>




{% endblock content%}

todaApp/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>M-Todo</title>
    <!-- CSS -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/all.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/all.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
</head>
<body>
    <div class="main-content">
            {% block content %} {% endblock content%} 
    </div>

    <!-- JS -->
    <script src="{{url_for('static', filename='js/jquery.3.4.1.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/all.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
</body>
</html>

todaApp/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <div class="inner-content">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Log In</legend>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
                </small>
            </div>
        </div>
    </div>
    
{% endblock content %}

todaApp/templates/project.html
{% extends 'layout.html'%}

{% block content %}
<div class="wrapper">
    {% include 'sidebar.html' %}
    <div id="project-single">
        <!-- Toggler  -->
        <div class="toggler">
            <button type="button" id="sidebarCollapse" class="btn btn-info">
                <i class="fas fa-align-left"></i>
                <span></span>
            </button>
        </div>

        <!-- Task -->
        <div class="task-content">

            <div class="scroll-area-sm">
                <perfect-scrollbar class="ps-show-limits">
                    <div style="position: static;" class="ps ps--active-y">
                        <!-- project -->
                        <div class="project-info">
                            <h2>{{project.title | upper}}</h2>
                            <div class="badge badge-success">
                                {{project.due_date.strftime('%d-%m-%Y')}}
                            </div>
                            <br>
                            <i>{{project.description}}</i>
                            <br>
                            <br>
                            <button class="border-0 btn-transition btn btn-outline-primary">
                                <a href="{{ url_for('tasks.update_project', project_id=project.id) }}"><i
                                        class="far fa-edit"></i></a>
                            </button>
                            <button class="border-0 btn-transition btn btn-outline-danger">
                                <a href="{{ url_for('tasks.delete_project', project_id=project.id) }}"><i
                                        class="fa fa-trash"></i> </a>
                            </button>
                        </div>
                        <!-- div task -->
                        <div class="ps-content">
                            <h5>On Going Tasks</h5>
                            <ul class=" list-group list-group-flush">
                                {% for task in tasks %}
                                <li class="list-group-item">
                                    <div class="todo-indicator bg-warning"></div>
                                    <div class="widget-content p-0">
                                        <div class="widget-content-wrapper">
                                            <div class="widget-content-left mr-2">
                                                <button class="border-0 btn-transition btn btn-outline-primary">
                                                    <a href="{{ url_for('tasks.complete_task', todo_id=task.id) }}">
                                                        <i class="fa fa-check"></i>
                                                    </a>
                                                </button>
                                            </div>
                                            <div class="widget-content-left">
                                                <div class="widget-heading">{{task.title}} <div
                                                        class="badge badge-success ml-2">
                                                        {{task.due_date.strftime('%d-%m-%Y')}}</div>
                                                </div>
                                                <div class="widget-subheading">
                                                    <a href="{{url_for('tasks.update_project', project_id=task.project)}}"><strong>{{ task.task.title}}</strong></a> <br>
                                                    <i>{{task.description}}</i>
                                                </div>
                                            </div>
                                            <div class="widget-content-right">
                                                <button class="border-0 btn-transition btn btn-outline-primary">
                                                    <a href="{{ url_for('tasks.update_task', todo_id=task.id) }}"><i
                                                            class="far fa-edit"></i></a>
                                                </button>
                                                <button class="border-0 btn-transition btn btn-outline-danger">
                                                    <a href="{{ url_for('tasks.delete_task', todo_id=task.id) }}"><i
                                                            class="fa fa-trash"></i> </a>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>

                            <!-- completed task -->
                            <br>
                            <br>
                            <h5>Completed Tasks</h5>
                            <ul class=" list-group list-group-flush">
                                {% for ctask in tasks_complete %}
                                <li class="list-group-item">
                                    <div class="todo-indicator bg-warning"></div>
                                    <div class="widget-content p-0">
                                        <div class="widget-content-wrapper" style="opacity: 0.2;">
                                            <div class="widget-content-left mr-2">
                                                <button class="border-0 btn-transition btn btn-outline-primary">
                                                    <a href="{{ url_for('tasks.complete_task', todo_id=ctask.id) }}">
                                                        <i class="fa fa-times"></i>
                                                    </a>
                                                </button>
                                            </div>
                                            <div class="widget-content-left">
                                                <div class="widget-heading">{{ctask.title}} <div
                                                        class="badge badge-success ml-2">
                                                        {{ctask.due_date.strftime('%d-%m-%Y')}}</div>
                                                </div>
                                                <div class="widget-subheading">
                                                    <a href="{{url_for('tasks.update_project', project_id=ctask.project)}}"><strong>{{ ctask.task.title}}</strong></a> <br>
                                                    <i>{{ctask.description}}</i>
                                                </div>
                                            </div>
                                            <div class="widget-content-right">
                                                <button class="border-0 btn-transition btn btn-outline-primary">
                                                    <a href="{{ url_for('tasks.update_task', todo_id=ctask.id) }}">
                                                        <i class="far fa-edit"></i>
                                                    </a>
                                                </button>
                                                <button class="border-0 btn-transition btn btn-outline-danger">
                                                    <a href="{{ url_for('tasks.delete_task', todo_id=ctask.id) }}">
                                                        <i class="fa fa-trash"></i>
                                                    </a>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                            <!-- end completed task -->
                          
                        </div>
                    </div>
                </perfect-scrollbar>
            </div>
            <div class="d-block text-right card-footer">
                <a href="{{url_for('tasks.newProject')}}"> <button class="btn btn-success">Add Project</button></a>
                <a href="{{url_for('tasks.newTask')}}"><button class="btn btn-primary">Add Task</button></a>
            </div>
            <!-- Batas -->
        </div>

    </div>

</div>




{% endblock content%}

todaApp/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

todaApp/templates/sidebar.html
<!-- Sidebar  -->
<nav id="sidebar">
    <div class="sidebar-header">
        <h3>M-Todo</h3>
    </div>

    <ul class="list-unstyled components">
        <p>{{current_user.username | upper}}</p>
        <li>
            <a href="{{ url_for('main.home')}}">Home</a>
        </li>
        <li>
            <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Project</a>
            <ul class="collapse list-unstyled" id="pageSubmenu">
                {% for project in projects %}
                    <li>
                        <a href="{{ url_for('tasks.single_project', project_id=project.id)}}">{{project.title}}</a>
                    </li>
                {% endfor %}
            </ul>
        </li>
        <li>
            <a href="{{ url_for('users.account')}}">Account</a>
        </li>
    </ul>

    <ul class="list-unstyled CTAs">
        <li>
            <a href="{{url_for('users.logout')}}" class="download">Logout</a>
        </li>
    </ul>
</nav>